FROM python:3.8.2-alpine3.11
RUN mkdir /executor
COPY async_test_server.py /executor/server.py
COPY requirements.txt /executor/requirements.txt
WORKDIR /executor
RUN pip3 install -r requirements.txt
EXPOSE 8888
ENTRYPOINT python3 /executor/server.py
